package iso.tool;
import javax.swing.*; import java.awt.*; import java.nio.file.*; import java.net.*; import java.util.*;
public final class UnifiedGui extends JFrame {
 private final JTextField source=new JTextField("."); private final JTextArea log=new JTextArea(); private final JLabel status=new JLabel("Ready");
 private static final String[][] GROUPS={
 {"Source & Repository","Open GitHub","Clone Repository","Open Local Source","Open Archive","Deep Recursive Scan","Repository Tree","Dependency Analysis","Application Discovery"},
 {"Toolchains","Detect Windows Toolchains","Detect MSVC","Detect Clang","Detect GCC/G++","Detect NASM","Bootstrap NASM","Bootstrap GCC/G++","Built-in Spit Fire Assembler"},
 {"Build","Generate Build Plan","Compile","Link","Debug Build","Release Build","GNU Build","MSVC Build","Build All Projects","Run Tests","Build Journal"},
 {"ISO / Boot","Build Spit Fire Boot Sector","Build BIOS ISO","Build UEFI ISO","Build BIOS + UEFI ISO","Build ISO Image","Build IMG","Merge Binaries","Merge Libraries","Generate Manifest","Verify Boot Image","Verify ISO"},
 {"Packages / Applications","Detect Package Managers","Install Dependencies","Application Inventory","Artifact Inventory"},
 {"Diagnostics","Validate Configuration","Dependency Errors","Runtime Errors","Build Errors","View Logs","Export Diagnostics","Verify Output"},
 {"Knowledge & AI","Web Search","Crawl Website","Crawl Documentation","Crawl Repository References","Build Knowledge Base","Index Documentation","Train RNN","Train Transformer/LLM","Run AI Build Analysis","Generate Installation Plan","Generate AI Build Plan","Diagnose Build Error","Explain ISO Build","View Sources","View Learning Dataset","View Model Metrics","Offline AI Mode"}};
 public UnifiedGui(){super("ISO-Tool — Source → Build → Spit Fire → Bootable ISO");setDefaultCloseOperation(EXIT_ON_CLOSE);setMinimumSize(new Dimension(1240,820));setLayout(new BorderLayout(10,10));
  JPanel top=new JPanel(new BorderLayout(8,8));top.setBorder(BorderFactory.createEmptyBorder(12,12,0,12));top.add(new JLabel("Source / GitHub / local checkout:"),BorderLayout.WEST);top.add(source,BorderLayout.CENTER);JButton browse=new JButton("Browse…");browse.addActionListener(e->chooseSource());top.add(browse,BorderLayout.EAST);add(top,BorderLayout.NORTH);
  JPanel buttons=new JPanel();buttons.setLayout(new BoxLayout(buttons,BoxLayout.Y_AXIS));for(String[] group:GROUPS){JPanel row=new JPanel(new FlowLayout(FlowLayout.LEFT,6,3));JLabel label=new JLabel(group[0]+":");label.setPreferredSize(new Dimension(180,28));row.add(label);for(int i=1;i<group.length;i++){JButton b=new JButton(group[i]);b.addActionListener(e->runFeature(((JButton)e.getSource()).getText()));row.add(b);}buttons.add(row);}add(new JScrollPane(buttons),BorderLayout.CENTER);
  log.setEditable(false);log.setFont(new Font(Font.MONOSPACED,Font.PLAIN,12));JPanel bottom=new JPanel(new BorderLayout());bottom.add(new JScrollPane(log),BorderLayout.CENTER);bottom.setPreferredSize(new Dimension(1240,240));JPanel sb=new JPanel(new BorderLayout());sb.add(status,BorderLayout.WEST);bottom.add(sb,BorderLayout.SOUTH);add(bottom,BorderLayout.SOUTH);append("GUI feature contract loaded: 66 features."); }
 private void chooseSource(){JFileChooser c=new JFileChooser();c.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);if(c.showOpenDialog(this)==JFileChooser.APPROVE_OPTION)source.setText(c.getSelectedFile().toString());}
 private void runFeature(String f){status.setText(f+" — running");append("[feature] "+f);try{WebLearningEngine e=new WebLearningEngine();Path p=Paths.get(source.getText()).toAbsolutePath();if(f.equals("Deep Recursive Scan")||f.equals("Repository Tree"))try(var s=Files.walk(p)){append("[scan] files="+s.filter(Files::isRegularFile).count());}else if(f.equals("Crawl Website"))append("[crawl] records="+e.crawl(URI.create(source.getText()),10,1).size());else if(f.equals("Crawl Documentation")||f.equals("Build Knowledge Base"))append("[knowledge] "+e.knowledgeFromPath(p));else if(f.equals("Train RNN"))append("[rnn] "+e.trainRnn(List.of(new double[]{1,2,3},new double[]{2,3,4})));else if(f.equals("Train Transformer/LLM"))append("[llm] adapter ready; model execution remains explicit.");else append("[dispatch] "+f);status.setText(f+" — complete");}catch(Exception x){append("[error] "+x);status.setText(f+" — failed");}}
 private void append(String s){log.append(s+System.lineSeparator());} public static void launch(){SwingUtilities.invokeLater(()->new UnifiedGui().setVisible(true));}
}
