FROM python:3.12-slim
WORKDIR /app
COPY server/requirements.txt server/requirements.txt
RUN pip install --no-cache-dir -r server/requirements.txt
COPY . .
EXPOSE 8010
CMD ["uvicorn","server.app:app","--host","0.0.0.0","--port","8010"]
