CREATE DATABASE IF NOT EXISTS NLP;
CREATE SCHEMA IF NOT EXISTS NLP.OLAP;
CREATE OR REPLACE TABLE NLP.OLAP.DIM_SCRIPT (SCRIPT_KEY NUMBER PRIMARY KEY, CANONICAL_CODE VARCHAR(64), SCRIPT_NAME VARCHAR(200), FAMILY_NAME VARCHAR(200), DECIPHERMENT_STATUS VARCHAR(32));
CREATE OR REPLACE TABLE NLP.OLAP.DIM_MODEL (MODEL_KEY NUMBER PRIMARY KEY, MODEL_NAME VARCHAR(256), ARCHITECTURE VARCHAR(128), VERSION VARCHAR(128), FRAMEWORK VARCHAR(128));
CREATE OR REPLACE TABLE NLP.OLAP.DIM_LANGUAGE (LANGUAGE_KEY NUMBER PRIMARY KEY, LANGUAGE_CODE VARCHAR(64), LANGUAGE_NAME VARCHAR(200));
CREATE OR REPLACE TABLE NLP.OLAP.DIM_DATE (DATE_KEY NUMBER PRIMARY KEY, CALENDAR_DATE DATE, YEAR_NUMBER NUMBER, QUARTER_NUMBER NUMBER, MONTH_NUMBER NUMBER, DAY_NUMBER NUMBER);
CREATE OR REPLACE TABLE NLP.OLAP.FACT_OCR_TRANSLATION (FACT_KEY NUMBER PRIMARY KEY, DATE_KEY NUMBER, SCRIPT_KEY NUMBER, MODEL_KEY NUMBER, SOURCE_LANGUAGE_KEY NUMBER, TARGET_LANGUAGE_KEY NUMBER, GLYPH_COUNT NUMBER, TOKEN_COUNT NUMBER, CONFIDENCE NUMBER(9,6), LATENCY_MS NUMBER(20,3), TRANSLATION_COUNT NUMBER, HUMAN_VERIFIED_COUNT NUMBER);
