CREATE TABLE script_family (script_id RAW(16) DEFAULT SYS_GUID() PRIMARY KEY, canonical_code VARCHAR2(64) NOT NULL UNIQUE, name VARCHAR2(200) NOT NULL, family VARCHAR2(200), writing_direction VARCHAR2(16) DEFAULT 'unknown' NOT NULL, decipherment_status VARCHAR2(32) DEFAULT 'partial' NOT NULL, created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL);
CREATE TABLE source_document (document_id RAW(16) DEFAULT SYS_GUID() PRIMARY KEY, external_id VARCHAR2(256), title CLOB, uri CLOB, media_type VARCHAR2(128), checksum_sha256 CHAR(64), captured_at TIMESTAMP WITH TIME ZONE, created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL);
CREATE TABLE inscription (inscription_id RAW(16) DEFAULT SYS_GUID() PRIMARY KEY, document_id RAW(16) REFERENCES source_document(document_id), script_id RAW(16) NOT NULL REFERENCES script_family(script_id), scholarly_id VARCHAR2(256), language_code VARCHAR2(64), transliteration CLOB, translation CLOB, confidence NUMBER(6,5), uncertainty CLOB, provenance CLOB, created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL);
CREATE TABLE glyph_observation (glyph_id RAW(16) DEFAULT SYS_GUID() PRIMARY KEY, inscription_id RAW(16) NOT NULL REFERENCES inscription(inscription_id) ON DELETE CASCADE, sequence_no NUMBER(10) NOT NULL, unicode_codepoint VARCHAR2(32), glyph_label VARCHAR2(128), bounding_box CLOB, image_uri CLOB, recognized_text CLOB, confidence NUMBER(6,5), damaged NUMBER(1) DEFAULT 0 NOT NULL, alternate_readings CLOB, created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL, CONSTRAINT uq_glyph_seq UNIQUE(inscription_id,sequence_no));
CREATE TABLE reading (reading_id RAW(16) DEFAULT SYS_GUID() PRIMARY KEY, inscription_id RAW(16) NOT NULL REFERENCES inscription(inscription_id) ON DELETE CASCADE, reading_text CLOB NOT NULL, transliteration CLOB, normalized_text CLOB, confidence NUMBER(6,5), reviewer VARCHAR2(256), evidence CLOB, created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL);
CREATE TABLE translation_candidate (candidate_id RAW(16) DEFAULT SYS_GUID() PRIMARY KEY, reading_id RAW(16) NOT NULL REFERENCES reading(reading_id) ON DELETE CASCADE, target_language VARCHAR2(32) NOT NULL, translation CLOB NOT NULL, model_id RAW(16), confidence NUMBER(6,5), rank_no NUMBER(10), evidence CLOB, human_verified NUMBER(1) DEFAULT 0 NOT NULL, created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL);
CREATE TABLE model_registry (model_id RAW(16) DEFAULT SYS_GUID() PRIMARY KEY, model_name VARCHAR2(256) NOT NULL UNIQUE, architecture VARCHAR2(128), task VARCHAR2(128), provider VARCHAR2(256), license VARCHAR2(256), metadata CLOB, created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL);
CREATE TABLE model_version (model_version_id RAW(16) DEFAULT SYS_GUID() PRIMARY KEY, model_id RAW(16) NOT NULL REFERENCES model_registry(model_id), version VARCHAR2(128) NOT NULL, artifact_uri CLOB, checksum_sha256 CHAR(64), parameters NUMBER(19), framework VARCHAR2(128), metrics CLOB, created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL, CONSTRAINT uq_model_version UNIQUE(model_id,version));
CREATE TABLE inference_run (run_id RAW(16) DEFAULT SYS_GUID() PRIMARY KEY, model_version_id RAW(16) REFERENCES model_version(model_version_id), inscription_id RAW(16) REFERENCES inscription(inscription_id), operation VARCHAR2(64) NOT NULL, input_hash CHAR(64), output CLOB, latency_ms NUMBER(18,3), confidence NUMBER(6,5), created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL);
