using System.Diagnostics;
using System.Text.Json;
namespace Chimera.IsoTool;
public sealed class Dependency { public string Name=""; public string[] Commands=Array.Empty<string>(); public bool Required; public string Category=""; public string? Path; public string Status="missing"; public string? Version; }
public static class DependencyDetector {
 static readonly Dependency[] Specs={new(){Name="git",Commands=new[]{"git"},Required=true,Category="source"},new(){Name="python",Commands=new[]{"python","python3"},Required=true,Category="runtime"},new(){Name="cmake",Commands=new[]{"cmake"},Required=true,Category="build"},new(){Name="gcc",Commands=new[]{"gcc"},Category="compiler"},new(){Name="g++",Commands=new[]{"g++"},Category="compiler"},new(){Name="msvc",Commands=new[]{"cl"},Category="compiler"},new(){Name="clang",Commands=new[]{"clang"},Category="compiler"},new(){Name="lld",Commands=new[]{"lld"},Category="linker"},new(){Name="nasm",Commands=new[]{"nasm"},Category="assembler"},new(){Name="masm",Commands=new[]{"ml","ml64"},Category="assembler"},new(){Name="ninja",Commands=new[]{"ninja"},Category="build"},new(){Name="msbuild",Commands=new[]{"msbuild"},Category="build"},new(){Name="xorriso",Commands=new[]{"xorriso","xorrisofs"},Category="image"},new(){Name="oscdimg",Commands=new[]{"oscdimg"},Category="image"},new(){Name="qemu",Commands=new[]{"qemu-system-x86_64"},Category="verification"},new(){Name="java",Commands=new[]{"java"},Category="runtime"},new(){Name="javac",Commands=new[]{"javac"},Category="compiler"},new(){Name="dotnet",Commands=new[]{"dotnet"},Category="runtime"},new(){Name="node",Commands=new[]{"node"},Category="runtime"},new(){Name="go",Commands=new[]{"go"},Category="compiler"},new(){Name="rustc",Commands=new[]{"rustc"},Category="compiler"},new(){Name="7zip",Commands=new[]{"7z","7zz"},Category="archive"}};
 public static IReadOnlyList<Dependency> Detect(){var result=new List<Dependency>();foreach(var spec in Specs){var d=new Dependency{Name=spec.Name,Commands=spec.Commands,Required=spec.Required,Category=spec.Category};foreach(var c in d.Commands){try{using var p=Process.Start(new ProcessStartInfo(c,"--version"){UseShellExecute=false,RedirectStandardOutput=true,RedirectStandardError=true,CreateNoWindow=true});if(p==null)continue;d.Path=c;p.WaitForExit(1500);d.Version=(p.StandardOutput.ReadToEnd()+p.StandardError.ReadToEnd()).Split('\n')[0].Trim();break;}catch{}}d.Status=d.Path==null?"missing":"found";result.Add(d);}return result;}
 public static string ToJson(){var d=Detect();return JsonSerializer.Serialize(new{dependencies=d,summary=new{found=d.Count(x=>x.Status=="found"),missing=d.Count(x=>x.Status=="missing"),required_missing=d.Count(x=>x.Status=="missing"&&x.Required)}},new JsonSerializerOptions{WriteIndented=true});}
}
