using System.Net; using System.Net.Http; using System.Security.Cryptography; using System.Text.RegularExpressions;
namespace ISOTool;
public sealed record WebRecord(string Url,string Title,string Text,string RetrievedAt,string Sha256,string SourceType,int Status);
public sealed class WebLearningEngine {
 readonly HttpClient client=new(); readonly Dictionary<string,(DateTimeOffset, string)> robots=new();
 public async Task<IReadOnlyList<WebRecord>> CrawlAsync(Uri start,int maxPages=20,int maxDepth=2,CancellationToken ct=default){if(start.Scheme is not("http" or "https"))throw new ArgumentException("HTTP(S) only");var q=new Queue<(Uri,int)>();q.Enqueue((start,0));var seen=new HashSet<string>();var outp=new List<WebRecord>();
  while(q.Count>0&&outp.Count<maxPages){var(u,d)=q.Dequeue();if(!seen.Add(u.AbsoluteUri)||d>maxDepth||!await AllowedAsync(u,ct))continue;using var r=await client.GetAsync(u,ct);var body=await r.Content.ReadAsStringAsync(ct);var text=Regex.Replace(Regex.Replace(body,"(?is)<(script|style).*?</\\1>"," "),"<[^>]+>"," ");text=Regex.Replace(text,"\\s+"," ").Trim();var title=Regex.Match(body,"(?is)<title[^>]*>(.*?)</title>").Groups[1].Value.Trim();var hash=Convert.ToHexString(SHA256.HashData(System.Text.Encoding.UTF8.GetBytes(body))).ToLowerInvariant();outp.Add(new(u.AbsoluteUri,title,text,DateTimeOffset.UtcNow.ToString("O"),hash,"web",(int)r.StatusCode));if(d<maxDepth)foreach(Match m in Regex.Matches(body,"(?is)href\\s*=\\s*[\\\"']([^\\\"']+)")){if(Uri.TryCreate(u,m.Groups[1].Value,out var n)&&n.Host==u.Host)q.Enqueue((n,d+1));}}
  return outp; }
 async Task<bool> AllowedAsync(Uri u,CancellationToken ct){try{var r=new UriBuilder(u.Scheme,u.Host,"/robots.txt").Uri;var key=r.AbsoluteUri;if(robots.TryGetValue(key,out var c)&&DateTimeOffset.UtcNow-c.Item1<TimeSpan.FromHours(24))return c.Item2!="DISALLOW_ALL";var text=await client.GetStringAsync(r,ct);robots[key]=(DateTimeOffset.UtcNow,text);foreach(var line in text.Split('\n'))if(line.Trim().Equals("Disallow: /",StringComparison.OrdinalIgnoreCase))return false;return true;}catch{return false;}}
 public static Dictionary<string,object> TrainRnn(IEnumerable<double[]> sequences){double h=0,w=0;int n=0;foreach(var seq in sequences){foreach(var x in seq){h=Math.Tanh(x*.1+h*.05);w+=h*.01;}n++;}return new(){["backend"]="builtin-rnn",["samples"]=n,["confidence"]=1/(1+Math.Exp(-w)),["authorizationRequired"]=true};}
 public static Dictionary<string,object> LlmAdapter(string endpoint,string prompt)=>new(){["endpoint"]=endpoint,["prompt"]=prompt,["authorizationRequired"]=true};
}
