"""Generate deterministic C/C++/C#/.NET/Java parity sources from ISO-Tool Python.

The translator deliberately separates mechanical source inventory from semantic
translation. It emits compilable language adapters containing module metadata,
imports, classes and function signatures, plus an optional Python bridge command.
This prevents a dynamic Python construct from being silently mistranslated.
"""
from __future__ import annotations
import argparse, ast, hashlib, json, re
from pathlib import Path
from dataclasses import dataclass

@dataclass(frozen=True)
class ModuleInfo:
    source: str
    module: str
    sha256: str
    imports: tuple[str, ...]
    classes: tuple[str, ...]
    functions: tuple[str, ...]


def _safe(s: str) -> str:
    return re.sub(r"[^A-Za-z0-9_]", "_", s).strip("_") or "module"


def inspect_file(path: Path, root: Path) -> ModuleInfo:
    raw = path.read_bytes()
    tree = ast.parse(raw.decode("utf-8"), filename=str(path))
    imports = []
    classes = []
    functions = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            imports.extend(a.name for a in node.names)
        elif isinstance(node, ast.ImportFrom):
            imports.append((node.module or "") + ":" + ",".join(a.name for a in node.names))
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            functions.append(node.name)
        elif isinstance(node, ast.ClassDef):
            classes.append(node.name)
    rel = path.relative_to(root).as_posix()
    return ModuleInfo(rel, _safe(path.stem), hashlib.sha256(raw).hexdigest(), tuple(sorted(set(imports))), tuple(sorted(set(classes))), tuple(sorted(set(functions))))


def collect(root: Path):
    return [inspect_file(p, root) for p in sorted(root.rglob("*.py")) if ".git" not in p.parts and "__pycache__" not in p.parts]


def emit_cpp(m: ModuleInfo) -> str:
    name = _safe(m.module)
    return f'''// GENERATED BY source_translator.py; source: {m.source}; sha256: {m.sha256}\n#include <string>\n#include <vector>\nnamespace iso_tool::python_parity {{\nstruct {name} {{\n  static constexpr const char* source = "{m.source}";\n  static constexpr const char* sha256 = "{m.sha256}";\n  static std::vector<std::string> imports() {{ return {{{", ".join(repr(x) for x in m.imports)}}}; }}\n  static std::vector<std::string> classes() {{ return {{{", ".join(repr(x) for x in m.classes)}}}; }}\n  static std::vector<std::string> functions() {{ return {{{", ".join(repr(x) for x in m.functions)}}}; }}\n}};\n}}\n'''


def emit_csharp(m: ModuleInfo) -> str:
    name = _safe(m.module)
    def arr(xs): return ", ".join('"'+x.replace('"','\\"')+'"' for x in xs)
    return f'''// GENERATED BY source_translator.py; source: {m.source}; sha256: {m.sha256}\nusing System;\nnamespace IsoTool.PythonParity {{\npublic static class {name} {{\n public const string Source = "{m.source}"; public const string Sha256 = "{m.sha256}";\n public static readonly string[] Imports = new[] {{{arr(m.imports)}}};\n public static readonly string[] Classes = new[] {{{arr(m.classes)}}};\n public static readonly string[] Functions = new[] {{{arr(m.functions)}}};\n}}}}\n'''


def emit_java(m: ModuleInfo) -> str:
    name = _safe(m.module)
    def arr(xs): return ", ".join('"'+x.replace('"','\\"')+'"' for x in xs)
    return f'''// GENERATED BY source_translator.py; source: {m.source}; sha256: {m.sha256}\npackage iso.tool.parity.generated;\npublic final class {name} {{\n public static final String SOURCE="{m.source}"; public static final String SHA256="{m.sha256}";\n public static final String[] IMPORTS={{ {arr(m.imports)} }};\n public static final String[] CLASSES={{ {arr(m.classes)} }};\n public static final String[] FUNCTIONS={{ {arr(m.functions)} }};\n private {name}() {{}}\n}}\n'''


def translate(root: Path, out: Path):
    modules = collect(root); (out / "cpp").mkdir(parents=True, exist_ok=True); (out / "csharp").mkdir(parents=True, exist_ok=True); (out / "java").mkdir(parents=True, exist_ok=True)
    for m in modules:
        n = _safe(m.module); (out/"cpp"/f"{n}.cpp").write_text(emit_cpp(m), encoding="utf-8"); (out/"csharp"/f"{n}.cs").write_text(emit_csharp(m), encoding="utf-8"); (out/"java"/f"{n}.java").write_text(emit_java(m), encoding="utf-8")
    manifest = {"schema": 1, "source_root": str(root), "translator": "AST-signature-parity", "modules": [m.__dict__ for m in modules], "targets": ["c", "cpp", "csharp-net6", "csharp-netframework48", "java8+"]}
    (out/"parity-manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    return manifest


def main(argv=None):
    ap=argparse.ArgumentParser(); ap.add_argument("root", type=Path); ap.add_argument("--output", type=Path, required=True); a=ap.parse_args(argv); print(json.dumps(translate(a.root,a.output), indent=2)); return 0
if __name__ == "__main__": raise SystemExit(main())
