IF DB_ID(N'NLP') IS NULL CREATE DATABASE NLP;
GO
USE NLP;
GO
IF OBJECT_ID('dbo.script_family','U') IS NULL CREATE TABLE dbo.script_family (script_id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(), canonical_code NVARCHAR(64) NOT NULL UNIQUE, name NVARCHAR(200) NOT NULL, family NVARCHAR(200), writing_direction NVARCHAR(16) NOT NULL DEFAULT N'unknown', decipherment_status NVARCHAR(32) NOT NULL DEFAULT N'partial', created_at DATETIME2(6) NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('dbo.source_document','U') IS NULL CREATE TABLE dbo.source_document (document_id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(), external_id NVARCHAR(256), title NVARCHAR(MAX), uri NVARCHAR(MAX), media_type NVARCHAR(128), checksum_sha256 CHAR(64), captured_at DATETIME2(6), created_at DATETIME2(6) NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('dbo.inscription','U') IS NULL CREATE TABLE dbo.inscription (inscription_id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(), document_id UNIQUEIDENTIFIER NULL REFERENCES dbo.source_document(document_id), script_id UNIQUEIDENTIFIER NOT NULL REFERENCES dbo.script_family(script_id), scholarly_id NVARCHAR(256), language_code NVARCHAR(64), transliteration NVARCHAR(MAX), translation NVARCHAR(MAX), confidence DECIMAL(6,5), uncertainty NVARCHAR(MAX), provenance NVARCHAR(MAX), created_at DATETIME2(6) NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('dbo.glyph_observation','U') IS NULL CREATE TABLE dbo.glyph_observation (glyph_id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(), inscription_id UNIQUEIDENTIFIER NOT NULL REFERENCES dbo.inscription(inscription_id) ON DELETE CASCADE, sequence_no INT NOT NULL, unicode_codepoint NVARCHAR(32), glyph_label NVARCHAR(128), bounding_box NVARCHAR(MAX), image_uri NVARCHAR(MAX), recognized_text NVARCHAR(MAX), confidence DECIMAL(6,5), damaged BIT NOT NULL DEFAULT 0, alternate_readings NVARCHAR(MAX), created_at DATETIME2(6) NOT NULL DEFAULT SYSUTCDATETIME(), CONSTRAINT uq_glyph_seq UNIQUE(inscription_id,sequence_no));
IF OBJECT_ID('dbo.reading','U') IS NULL CREATE TABLE dbo.reading (reading_id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(), inscription_id UNIQUEIDENTIFIER NOT NULL REFERENCES dbo.inscription(inscription_id) ON DELETE CASCADE, reading_text NVARCHAR(MAX) NOT NULL, transliteration NVARCHAR(MAX), normalized_text NVARCHAR(MAX), confidence DECIMAL(6,5), reviewer NVARCHAR(256), evidence NVARCHAR(MAX), created_at DATETIME2(6) NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('dbo.translation_candidate','U') IS NULL CREATE TABLE dbo.translation_candidate (candidate_id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(), reading_id UNIQUEIDENTIFIER NOT NULL REFERENCES dbo.reading(reading_id) ON DELETE CASCADE, target_language NVARCHAR(32) NOT NULL, translation NVARCHAR(MAX) NOT NULL, model_id UNIQUEIDENTIFIER NULL, confidence DECIMAL(6,5), rank_no INT, evidence NVARCHAR(MAX), human_verified BIT NOT NULL DEFAULT 0, created_at DATETIME2(6) NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('dbo.model_registry','U') IS NULL CREATE TABLE dbo.model_registry (model_id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(), model_name NVARCHAR(256) NOT NULL UNIQUE, architecture NVARCHAR(128), task NVARCHAR(128), provider NVARCHAR(256), license NVARCHAR(256), metadata NVARCHAR(MAX), created_at DATETIME2(6) NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('dbo.model_version','U') IS NULL CREATE TABLE dbo.model_version (model_version_id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(), model_id UNIQUEIDENTIFIER NOT NULL REFERENCES dbo.model_registry(model_id), version NVARCHAR(128) NOT NULL, artifact_uri NVARCHAR(MAX), checksum_sha256 CHAR(64), parameters BIGINT, framework NVARCHAR(128), metrics NVARCHAR(MAX), created_at DATETIME2(6) NOT NULL DEFAULT SYSUTCDATETIME(), CONSTRAINT uq_model_version UNIQUE(model_id,version));
IF OBJECT_ID('dbo.inference_run','U') IS NULL CREATE TABLE dbo.inference_run (run_id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(), model_version_id UNIQUEIDENTIFIER NULL REFERENCES dbo.model_version(model_version_id), inscription_id UNIQUEIDENTIFIER NULL REFERENCES dbo.inscription(inscription_id), operation NVARCHAR(64) NOT NULL, input_hash CHAR(64), output NVARCHAR(MAX), latency_ms DECIMAL(18,3), confidence DECIMAL(6,5), created_at DATETIME2(6) NOT NULL DEFAULT SYSUTCDATETIME());
