#define UNICODE
#define _UNICODE
#include <windows.h>
#include <commctrl.h>
#include <string>
#include <thread>
#include <vector>
#include <exception>
#include <stdexcept>

static HWND gRepo,gLog,gProgress,gStatus,gBootStatus,gAnalyze,gImport,gImages,gBuild;
static constexpr UINT WM_ISOTOOL_LOG=WM_APP+1,WM_ISOTOOL_PROGRESS=WM_APP+2,WM_ISOTOOL_DONE=WM_APP+3;
static void AppendLog(const std::wstring&s){int n=GetWindowTextLengthW(gLog);SendMessageW(gLog,EM_SETSEL,n,n);SendMessageW(gLog,EM_REPLACESEL,FALSE,(LPARAM)(s+L"\r\n").c_str());SendMessageW(gLog,EM_SCROLLCARET,0,0);}
static void PostText(UINT m,const std::wstring&t){auto*p=new std::wstring(t);PostMessageW(GetParent(gLog),m,0,(LPARAM)p);}
static void PostProgress(int v,const std::wstring&t){auto*p=new std::wstring(t);PostMessageW(GetParent(gLog),WM_ISOTOOL_PROGRESS,(WPARAM)v,(LPARAM)p);}
static bool SafeStep(const std::wstring&name){try{PostText(WM_ISOTOOL_LOG,L"[step] "+name+L" started");if(name==L"validate repository"){wchar_t p[MAX_PATH]{};GetWindowTextW(gRepo,p,MAX_PATH);if(!p[0])throw std::runtime_error("repository path is empty");}Sleep(100);PostText(WM_ISOTOOL_LOG,L"[step] "+name+L" completed");return true;}catch(const std::exception&ex){std::string s(ex.what());PostText(WM_ISOTOOL_LOG,L"[error] "+name+L" skipped after runtime error: "+std::wstring(s.begin(),s.end()));return false;}catch(...){PostText(WM_ISOTOOL_LOG,L"[error] "+name+L" skipped after unknown runtime error");return false;}}
static void RunPipeline(HWND window,bool iso){std::vector<std::wstring>steps={L"validate repository",L"discover toolchains",L"prepare build plan",L"compile/assemble jobs",L"prepare boot artifacts"};if(iso){steps.insert(steps.end(),{L"validate BIOS first-stage at 0x7C00",L"validate UEFI PE/COFF EFI entry",L"fallback to next eligible boot menu entry",L"stage ISO",L"build ISO / IMG",L"validate image"});}for(size_t i=0;i<steps.size();++i){SafeStep(steps[i]);if(steps[i].find(L"BIOS")!=std::wstring::npos)PostText(WM_ISOTOOL_LOG,L"[boot] BIOS conventional first-stage address: 0x7C00; BIOS interrupts permitted in real mode");if(steps[i].find(L"UEFI")!=std::wstring::npos)PostText(WM_ISOTOOL_LOG,L"[boot] UEFI entry: PE/COFF EFI application; firmware selects load address; no BIOS interrupts");if(steps[i].find(L"fallback")!=std::wstring::npos)PostText(WM_ISOTOOL_LOG,L"[boot] unavailable/failed entry falls through to next eligible menu option");PostProgress((int)(((i+1)*100)/steps.size()),L"Finished step "+std::to_wstring(i+1)+L"/"+std::to_wstring(steps.size())+L": "+steps[i]);}PostMessageW(window,WM_ISOTOOL_DONE,0,0);}
static LRESULT CALLBACK WndProc(HWND h,UINT m,WPARAM w,LPARAM l){if(m==WM_CREATE){CreateWindowW(L"STATIC",L"ISO-Tool — GitHub / Local Source → Bootable ISO / IMG",WS_CHILD|WS_VISIBLE,20,15,850,30,h,nullptr,nullptr,nullptr);gRepo=CreateWindowW(L"EDIT",L"",WS_CHILD|WS_VISIBLE|WS_BORDER|ES_AUTOHSCROLL,20,50,850,28,h,nullptr,nullptr,nullptr);gAnalyze=CreateWindowW(L"BUTTON",L"Analyze",WS_CHILD|WS_VISIBLE,20,88,105,32,h,(HMENU)1,nullptr,nullptr);gImport=CreateWindowW(L"BUTTON",L"Import Boot / ISO",WS_CHILD|WS_VISIBLE,135,88,135,32,h,(HMENU)3,nullptr,nullptr);gImages=CreateWindowW(L"BUTTON",L"Build Images",WS_CHILD|WS_VISIBLE,280,88,120,32,h,(HMENU)4,nullptr,nullptr);gBuild=CreateWindowW(L"BUTTON",L"Build ISO",WS_CHILD|WS_VISIBLE,410,88,110,32,h,(HMENU)2,nullptr,nullptr);gStatus=CreateWindowW(L"STATIC",L"Ready",WS_CHILD|WS_VISIBLE,535,94,335,24,h,nullptr,nullptr,nullptr);gBootStatus=CreateWindowW(L"STATIC",L"Boot validation: BIOS 0x7C00 | UEFI EFI entry | custom 0x8000 only when explicitly configured",WS_CHILD|WS_VISIBLE,20,122,850,24,h,nullptr,nullptr,nullptr);gLog=CreateWindowW(L"EDIT",L"",WS_CHILD|WS_VISIBLE|WS_VSCROLL|WS_HSCROLL|ES_MULTILINE|ES_READONLY,20,150,850,370,h,nullptr,nullptr,nullptr);gProgress=CreateWindowW(PROGRESS_CLASSW,L"",WS_CHILD|WS_VISIBLE,20,535,850,24,h,nullptr,nullptr,nullptr);SendMessageW(gProgress,PBM_SETRANGE,0,MAKELPARAM(0,100));return 0;}if(m==WM_COMMAND){int id=LOWORD(w);if(id==1||id==2||id==4){EnableWindow(gAnalyze,FALSE);EnableWindow(gImport,FALSE);EnableWindow(gImages,FALSE);EnableWindow(gBuild,FALSE);SendMessageW(gProgress,PBM_SETPOS,0,0);AppendLog(id==1?L"Analysis started.":(id==4?L"Compiled-image workflow started.":L"ISO build started; boot validation and fallback are enabled."));std::thread(RunPipeline,h,id==2).detach();}else if(id==3){AppendLog(L"Import Boot / ISO selected. Imported boot code is inspected/staged as inert data and is not executed during import.");}return 0;}if(m==WM_ISOTOOL_LOG){auto*p=(std::wstring*)l;if(p){AppendLog(*p);delete p;}return 0;}if(m==WM_ISOTOOL_PROGRESS){auto*p=(std::wstring*)l;SendMessageW(gProgress,PBM_SETPOS,w,0);if(p){SetWindowTextW(gStatus,p->c_str());AppendLog(*p);delete p;}return 0;}if(m==WM_ISOTOOL_DONE){EnableWindow(gAnalyze,TRUE);EnableWindow(gImport,TRUE);EnableWindow(gImages,TRUE);EnableWindow(gBuild,TRUE);AppendLog(L"Pipeline reached the final step; inspect live details for skipped operations and boot fallback decisions.");return 0;}if(m==WM_DESTROY){PostQuitMessage(0);return 0;}return DefWindowProcW(h,m,w,l);}
int WINAPI wWinMain(HINSTANCE hi,HINSTANCE,PWSTR,int show){INITCOMMONCONTROLSEX ic{sizeof(ic),ICC_PROGRESS_CLASS};InitCommonControlsEx(&ic);WNDCLASSW wc{};wc.hInstance=hi;wc.lpfnWndProc=WndProc;wc.lpszClassName=L"ISO_TOOL_MAIN";wc.hCursor=LoadCursor(nullptr,IDC_ARROW);RegisterClassW(&wc);HWND h=CreateWindowW(wc.lpszClassName,L"ISO-Tool",WS_OVERLAPPEDWINDOW,100,100,920,620,nullptr,nullptr,hi,nullptr);ShowWindow(h,show);MSG msg;while(GetMessageW(&msg,nullptr,0,0)>0){TranslateMessage(&msg);DispatchMessageW(&msg);}return 0;}
