#pragma once
#include <windows.h>
#include <string>
#include <vector>
#include <algorithm>
#include <filesystem>
#include <sstream>
#include <cstdio>

namespace iso_tool {
struct ToolInfo { std::wstring kind,name,path,version,source; };
inline std::wstring Trim(std::wstring s){auto a=s.find_first_not_of(L" \t\r\n");if(a==std::wstring::npos)return L"";auto b=s.find_last_not_of(L" \t\r\n");return s.substr(a,b-a+1);}
inline bool FileExists(const std::wstring&p){DWORD a=GetFileAttributesW(p.c_str());return a!=INVALID_FILE_ATTRIBUTES&&!(a&FILE_ATTRIBUTE_DIRECTORY);}
inline std::wstring SearchExecutable(const std::wstring&name){wchar_t out[32768]{};DWORD n=SearchPathW(nullptr,name.c_str(),nullptr,static_cast<DWORD>(std::size(out)),out,nullptr);return n&&n<std::size(out)?std::wstring(out,n):L"";}
inline std::wstring RunVersion(const std::wstring&exe){SECURITY_ATTRIBUTES sa{};sa.nLength=sizeof(sa);sa.bInheritHandle=TRUE;HANDLE r=nullptr,w=nullptr;if(!CreatePipe(&r,&w,&sa,0))return L"unknown version";SetHandleInformation(r,HANDLE_FLAG_INHERIT,0);std::wstring cmd=L"\""+exe+L"\" --version";std::vector<wchar_t>b(cmd.begin(),cmd.end());b.push_back(L'\0');STARTUPINFOW si{};si.cb=sizeof(si);si.dwFlags=STARTF_USESTDHANDLES;si.hStdOutput=w;si.hStdError=w;PROCESS_INFORMATION pi{};bool ok=CreateProcessW(nullptr,b.data(),nullptr,nullptr,TRUE,CREATE_NO_WINDOW,nullptr,nullptr,&si,&pi)!=FALSE;CloseHandle(w);if(!ok){CloseHandle(r);return L"unknown version";}WaitForSingleObject(pi.hProcess,1800);DWORD code=STILL_ACTIVE;GetExitCodeProcess(pi.hProcess,&code);if(code==STILL_ACTIVE){TerminateProcess(pi.hProcess,1);WaitForSingleObject(pi.hProcess,200);}std::string bytes;char chunk[512];DWORD got=0;while(ReadFile(r,chunk,sizeof(chunk),&got,nullptr)&&got)bytes.append(chunk,chunk+got);CloseHandle(r);CloseHandle(pi.hThread);CloseHandle(pi.hProcess);std::wstring wide(bytes.begin(),bytes.end());auto nl=wide.find_first_of(L"\r\n");if(nl!=std::wstring::npos)wide.resize(nl);return Trim(wide).empty()?L"unknown version":Trim(wide);}
inline void AddCandidate(std::vector<ToolInfo>&out,const std::wstring&kind,const std::wstring&name,const std::wstring&path,const std::wstring&source){if(!FileExists(path))return;for(const auto&x:out)if(_wcsicmp(x.path.c_str(),path.c_str())==0)return;out.push_back({kind,name,path,RunVersion(path),source});}
inline void ScanPath(std::vector<ToolInfo>&out,const std::wstring&kind,const std::vector<std::wstring>&names){for(const auto&n:names){auto p=SearchExecutable(n);if(!p.empty())AddCandidate(out,kind,n,p,L"PATH");}}
inline void ScanEnvironment(std::vector<ToolInfo>&c,std::vector<ToolInfo>&l,std::vector<ToolInfo>&a){
 const wchar_t*vars[]={L"VCINSTALLDIR",L"VCToolsInstallDir",L"VSINSTALLDIR",L"LLVMInstallDir",L"NASM_PREFIX",L"MINGW_HOME",L"MINGW64_HOME",L"CODEBLOCKS"};
 for(auto var:vars){DWORD n=GetEnvironmentVariableW(var,nullptr,0);if(!n)continue;std::vector<wchar_t>b(n);GetEnvironmentVariableW(var,b.data(),n);std::filesystem::path root(b.data());std::vector<std::filesystem::path> bases={root,root/L"bin",root/L"bin"/L"Hostx64"/L"x64"};for(auto base:bases){AddCandidate(c,L"C/C++ compiler",L"MSVC cl.exe",(base/L"cl.exe").wstring(),std::wstring(L"environment: ")+var);AddCandidate(c,L"C/C++ compiler",L"GNU g++.exe",(base/L"g++.exe").wstring(),std::wstring(L"environment: ")+var);AddCandidate(c,L"C/C++ compiler",L"LLVM clang++.exe",(base/L"clang++.exe").wstring(),std::wstring(L"environment: ")+var);AddCandidate(l,L"Linker",L"MSVC link.exe",(base/L"link.exe").wstring(),std::wstring(L"environment: ")+var);AddCandidate(l,L"Linker",L"LLVM lld-link.exe",(base/L"lld-link.exe").wstring(),std::wstring(L"environment: ")+var);AddCandidate(l,L"Linker",L"GNU ld.exe",(base/L"ld.exe").wstring(),std::wstring(L"environment: ")+var);AddCandidate(a,L"Assembler",L"MASM ml64.exe",(base/L"ml64.exe").wstring(),std::wstring(L"environment: ")+var);AddCandidate(a,L"Assembler",L"MASM ml.exe",(base/L"ml.exe").wstring(),std::wstring(L"environment: ")+var);AddCandidate(a,L"Assembler",L"NASM nasm.exe",(base/L"nasm.exe").wstring(),std::wstring(L"environment: ")+var);AddCandidate(a,L"Assembler",L"GNU as.exe",(base/L"as.exe").wstring(),std::wstring(L"environment: ")+var);}}
}
inline void ScanVisualStudioRegistry(std::vector<ToolInfo>&c,std::vector<ToolInfo>&l,std::vector<ToolInfo>&a){
 const wchar_t*keys[]={L"SOFTWARE\\Microsoft\\VisualStudio\\SxS\\VC7",L"SOFTWARE\\WOW6432Node\\Microsoft\\VisualStudio\\SxS\\VC7"};
 for(auto sub:keys){HKEY key=nullptr;if(RegOpenKeyExW(HKEY_LOCAL_MACHINE,sub,0,KEY_READ|KEY_WOW64_64KEY,&key)!=ERROR_SUCCESS)continue;for(DWORD i=0;;++i){wchar_t name[64]{},value[32768]{};DWORD nl=64,dl=sizeof(value),type=0;if(RegEnumValueW(key,i,name,&nl,nullptr,&type,reinterpret_cast<LPBYTE>(value),&dl)!=ERROR_SUCCESS)break;if(type!=REG_SZ)continue;std::filesystem::path base(value);base/=L"bin"/L"Hostx64"/L"x64";AddCandidate(c,L"C/C++ compiler",L"MSVC cl.exe",(base/L"cl.exe").wstring(),std::wstring(L"registry: ")+sub+L"\\"+name);AddCandidate(l,L"Linker",L"MSVC link.exe",(base/L"link.exe").wstring(),std::wstring(L"registry: ")+sub+L"\\"+name);AddCandidate(a,L"Assembler",L"MASM ml64.exe",(base/L"ml64.exe").wstring(),std::wstring(L"registry: ")+sub+L"\\"+name);AddCandidate(a,L"Assembler",L"MASM ml.exe",(base/L"ml.exe").wstring(),std::wstring(L"registry: ")+sub+L"\\"+name);}RegCloseKey(key);}
}
inline void DetectAll(std::vector<ToolInfo>&c,std::vector<ToolInfo>&l,std::vector<ToolInfo>&a){c.clear();l.clear();a.clear();ScanPath(c,L"C/C++ compiler",{L"cl.exe",L"g++.exe",L"clang++.exe",L"clang-cl.exe",L"gcc.exe"});ScanPath(l,L"Linker",{L"link.exe",L"lld-link.exe",L"ld.exe",L"ld.lld.exe"});ScanPath(a,L"Assembler",{L"ml64.exe",L"ml.exe",L"nasm.exe",L"yasm.exe",L"llvm-mc.exe",L"as.exe"});ScanEnvironment(c,l,a);ScanVisualStudioRegistry(c,l,a);auto s=[](auto&v){std::sort(v.begin(),v.end(),[](const ToolInfo&a,const ToolInfo&b){return a.name<b.name||a.name==b.name&&a.path<b.path;});};s(c);s(l);s(a);}
}
