#include <windows.h>
#include <string>
#include <vector>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <algorithm>
static HWND gLog{}; static HWND gSource{};
static const wchar_t* groups[][12]={{L"Source & Repository",L"Open GitHub",L"Clone Repository",L"Open Local Source",L"Open Archive",L"Deep Recursive Scan",L"Repository Tree",L"Dependency Analysis",L"Application Discovery"},{L"Toolchains",L"Detect Windows Toolchains",L"Detect MSVC",L"Detect Clang",L"Detect GCC/G++",L"Detect NASM",L"Bootstrap NASM",L"Bootstrap GCC/G++",L"Built-in Spit Fire Assembler"},{L"Build",L"Generate Build Plan",L"Compile",L"Link",L"Debug Build",L"Release Build",L"GNU Build",L"MSVC Build",L"Build All Projects",L"Run Tests",L"Build Journal"},{L"ISO / Boot",L"Build Spit Fire Boot Sector",L"Build BIOS ISO",L"Build UEFI ISO",L"Build BIOS + UEFI ISO",L"Build ISO Image",L"Build IMG",L"Merge Binaries",L"Merge Libraries",L"Generate Manifest",L"Verify Boot Image",L"Verify ISO"},{L"Packages / Applications",L"Detect Package Managers",L"Install Dependencies",L"Application Inventory",L"Artifact Inventory"},{L"Diagnostics",L"Validate Configuration",L"Dependency Errors",L"Runtime Errors",L"Build Errors",L"View Logs",L"Export Diagnostics",L"Verify Output"}};
static void log(const std::wstring&s){int n=GetWindowTextLengthW(gLog);SendMessageW(gLog,EM_SETSEL,n,n);std::wstring x=s+L"\r\n";SendMessageW(gLog,EM_REPLACESEL,FALSE,(LPARAM)x.c_str());}
static LRESULT CALLBACK WndProc(HWND h,UINT m,WPARAM w,LPARAM l){if(m==WM_CREATE){CreateWindowW(L"STATIC",L"ISO-Tool — Source → Build → Spit Fire → Bootable ISO",WS_CHILD|WS_VISIBLE,16,12,900,32,h,nullptr,nullptr,nullptr);gSource=CreateWindowW(L"EDIT",L".",WS_CHILD|WS_VISIBLE|WS_BORDER|ES_AUTOHSCROLL,16,50,760,30,h,(HMENU)900,nullptr,nullptr);int y=92;for(auto&g:groups){CreateWindowW(L"STATIC",g[0],WS_CHILD|WS_VISIBLE,16,y,175,26,h,nullptr,nullptr,nullptr);int x=190;for(int i=1;i<12&&g[i];++i){HWND b=CreateWindowW(L"BUTTON",g[i],WS_CHILD|WS_VISIBLE|BS_PUSHBUTTON,x,y,150,28,h,(HMENU)(1000+y+i),nullptr,nullptr);x+=154;if(x>1080){x=190;y+=34;}}y+=40;}gLog=CreateWindowW(L"EDIT",L"",WS_CHILD|WS_VISIBLE|WS_BORDER|WS_VSCROLL|ES_MULTILINE|ES_READONLY,16,y,1120,260,h,(HMENU)901,nullptr,nullptr);log(L"Unified C++ GUI ready; all feature groups are visible as buttons.");return 0;}if(m==WM_COMMAND&&HIWORD(w)==BN_CLICKED){wchar_t text[256]{};GetWindowTextW((HWND)l,text,256);log(std::wstring(L"[feature] ")+text);return 0;}if(m==WM_DESTROY){PostQuitMessage(0);return 0;}return DefWindowProcW(h,m,w,l);}
int WINAPI wWinMain(HINSTANCE hi,HINSTANCE, PWSTR, int show){WNDCLASSW wc{};wc.hInstance=hi;wc.lpfnWndProc=WndProc;wc.lpszClassName=L"ISO_TOOL_UNIFIED_GUI";wc.hCursor=LoadCursor(nullptr,IDC_ARROW);RegisterClassW(&wc);HWND h=CreateWindowW(wc.lpszClassName,wc.lpszClassName,WS_OVERLAPPEDWINDOW,CW_USEDEFAULT,CW_USEDEFAULT,1180,900,nullptr,nullptr,hi,nullptr);ShowWindow(h,show);MSG msg{};while(GetMessageW(&msg,nullptr,0,0)>0){TranslateMessage(&msg);DispatchMessageW(&msg);}return (int)msg.wParam;}
