#include "WebLearningEngine.hpp"
#include <windows.h>
#include <winhttp.h>
#include <regex>
#include <set>
#pragma comment(lib,"winhttp.lib")
static std::string getUrl(const std::wstring& u){URL_COMPONENTSW c{};wchar_t host[256]{},path[2048]{};c.dwStructSize=sizeof(c);c.lpszHostName=host;c.dwHostNameLength=256;c.lpszUrlPath=path;c.dwUrlPathLength=2048;if(!WinHttpCrackUrl(u.c_str(),0,0,&c))return {};std::wstring s=L"https://"+std::wstring(host)+std::wstring(path);int n=WideCharToMultiByte(CP_UTF8,0,s.c_str(),-1,nullptr,0,nullptr,nullptr);std::string o(n-1,'\0');WideCharToMultiByte(CP_UTF8,0,s.c_str(),-1,o.data(),n,nullptr,nullptr);return o;}
std::vector<WebRecord> WebLearningEngine::crawl(const std::string& start,int maxPages,int maxDepth){
 std::vector<WebRecord> out; std::vector<std::pair<std::string,int>> q{{start,0}}; std::set<std::string> seen;
 while(!q.empty()&&(int)out.size()<maxPages){auto [url,d]=q.front();q.erase(q.begin());if(!seen.insert(url).second||d>maxDepth)continue;URL_COMPONENTSA c{};char host[256]{},path[2048]{};c.dwStructSize=sizeof(c);c.lpszHostName=host;c.dwHostNameLength=256;c.lpszUrlPath=path;c.dwUrlPathLength=2048;std::wstring w(url.begin(),url.end());URL_COMPONENTSW wc{};wchar_t wh[256]{},wp[2048]{};wc.dwStructSize=sizeof(wc);wc.lpszHostName=wh;wc.dwHostNameLength=256;wc.lpszUrlPath=wp;wc.dwUrlPathLength=2048;if(!WinHttpCrackUrl(w.c_str(),0,0,&wc))continue;HINTERNET s=WinHttpOpen(L"ISO-Tool-Crawler/1.0",WINHTTP_ACCESS_TYPE_DEFAULT_PROXY,nullptr,nullptr,0);if(!s)continue;HINTERNET h=WinHttpConnect(s,wh, wc.nPort,0);if(!h){WinHttpCloseHandle(s);continue;}HINTERNET r=WinHttpOpenRequest(h,L"GET",wp,nullptr,WINHTTP_NO_REFERER,WINHTTP_DEFAULT_ACCEPT_TYPES,WINHTTP_FLAG_SECURE);if(!r||!WinHttpSendRequest(r,nullptr,0,nullptr,0,0,0)||!WinHttpReceiveResponse(r,nullptr)){if(r)WinHttpCloseHandle(r);WinHttpCloseHandle(h);WinHttpCloseHandle(s);continue;}std::string body;DWORD avail=0;while(WinHttpQueryDataAvailable(r,&avail)&&avail){std::string b(avail,'\0');DWORD got=0;if(!WinHttpReadData(r,b.data(),avail,&got)||!got)break;b.resize(got);body+=b;}WinHttpCloseHandle(r);WinHttpCloseHandle(h);WinHttpCloseHandle(s);std::string text=std::regex_replace(body,std::regex("<[^>]+>")," ");text=std::regex_replace(text,std::regex("[[:space:]]+")," ");out.push_back({url,"",text,"","web",200});if(d<maxDepth){std::regex a("href=[\\\"']([^\\\"']+)",std::regex::icase);for(auto i=std::sregex_iterator(body.begin(),body.end(),a);i!=std::sregex_iterator();++i){std::string n=(*i)[1];if(n.rfind("http",0)==0)q.push_back({n,d+1});}}}
 return out;
}
