#include "thamudic/thamudic.hpp"
#include <algorithm>
#include <queue>
#include <stdexcept>
namespace chimera::thamudic {
bool isThamudic(char32_t cp){return cp>=kFirst&&cp<=kLast;}
std::vector<char32_t> codePoints(std::u8string_view s){std::vector<char32_t>o;for(size_t i=0;i<s.size();){unsigned b=s[i];if(b<128){o.push_back(b);i++;}else if((b&224)==192&&i+1<s.size()){o.push_back(((b&31)<<6)|(s[i+1]&63));i+=2;}else if((b&240)==224&&i+2<s.size()){o.push_back(((b&15)<<12)|((s[i+1]&63)<<6)|(s[i+2]&63));i+=3;}else if((b&248)==240&&i+3<s.size()){o.push_back(((b&7)<<18)|((s[i+1]&63)<<12)|((s[i+2]&63)<<6)|(s[i+3]&63));i+=4;}else ++i;}return o;}
std::u8string toUtf8(std::u32string_view t){std::u8string o;for(char32_t c:t){if(c<128)o.push_back((char8_t)c);else if(c<2048){o.push_back((char8_t)(192|(c>>6)));o.push_back((char8_t)(128|(c&63)));}else if(c<65536){o.push_back((char8_t)(224|(c>>12)));o.push_back((char8_t)(128|((c>>6)&63)));o.push_back((char8_t)(128|(c&63)));}else{o.push_back((char8_t)(240|(c>>18)));o.push_back((char8_t)(128|((c>>12)&63)));o.push_back((char8_t)(128|((c>>6)&63)));o.push_back((char8_t)(128|(c&63)));}}return o;}
std::u32string extractThamudic(std::u32string_view t){std::u32string o;for(auto c:t)if(isThamudic(c))o.push_back(c);return o;}
std::string transliterate(std::u32string_view t,const std::unordered_map<char32_t,std::string>&m){std::string o;for(auto c:t){auto i=m.find(c);if(i!=m.end())o+=i->second;else if(c==U' '||c==U'\n'||c==U'\t')o+=' ';else if(isThamudic(c))o+='?';}return o;}
std::vector<Box> connectedComponents(const std::vector<uint8_t>&a,int w,int h,int minArea){if(w<=0||h<=0||(size_t)w*h!=a.size())throw std::invalid_argument("invalid image");std::vector<uint8_t>v(a.size());std::vector<Box>r;int dx[]={1,-1,0,0},dy[]={0,0,1,-1};for(int y=0;y<h;y++)for(int x=0;x<w;x++){size_t s=(size_t)y*w+x;if(v[s]||!a[s])continue;std::queue<std::pair<int,int>>q;q.push({x,y});v[s]=1;int x1=x,x2=x,y1=y,y2=y,n=0;while(!q.empty()){auto[cx,cy]=q.front();q.pop();n++;x1=std::min(x1,cx);x2=std::max(x2,cx);y1=std::min(y1,cy);y2=std::max(y2,cy);for(int k=0;k<4;k++){int nx=cx+dx[k],ny=cy+dy[k];if(nx>=0&&ny>=0&&nx<w&&ny<h){size_t z=(size_t)ny*w+nx;if(!v[z]&&a[z]){v[z]=1;q.push({nx,ny});}}}}if(n>=minArea)r.push_back({x1,y1,x2,y2});}return r;}
std::vector<std::vector<Box>> groupLines(std::vector<Box>b,int tol){std::sort(b.begin(),b.end(),[](auto&a,auto&z){return a.y1+a.y2<z.y1+z.y2;});std::vector<std::vector<Box>>r;for(auto x:b){double cy=(x.y1+x.y2)/2.0;bool p=false;for(auto&l:r){double m=0;for(auto q:l)m+=(q.y1+q.y2)/2.0;m/=l.size();if(std::abs(cy-m)<=tol){l.push_back(x);p=true;break;}}if(!p)r.push_back({x});}for(auto&l:r)std::sort(l.begin(),l.end(),[](auto&a,auto&z){return a.x1<z.x1;});return r;}
std::vector<std::vector<Box>> groupWords(const std::vector<Box>&l,int gap){if(l.empty())return{};std::vector<std::vector<Box>>r(1);for(size_t i=0;i<l.size();i++){if(i&&l[i].x1-l[i-1].x2>gap)r.push_back({});r.back().push_back(l[i]);}return r;}
}