CREATE COLUMN TABLE NLP.MDM_ENTITY (
  ENTITY_ID NVARCHAR(36) PRIMARY KEY,
  ENTITY_TYPE NVARCHAR(64) NOT NULL,
  CANONICAL_NAME NVARCHAR(512) NOT NULL,
  STATUS NVARCHAR(32) DEFAULT 'active' NOT NULL,
  SOURCE_SYSTEM NVARCHAR(128),
  SOURCE_KEY NVARCHAR(512),
  EFFECTIVE_FROM TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  EFFECTIVE_TO TIMESTAMP,
  RECORD_HASH NVARCHAR(128),
  ATTRIBUTES NCLOB
);
CREATE COLUMN TABLE NLP.MDM_CROSSWALK (
  CROSSWALK_ID NVARCHAR(36) PRIMARY KEY,
  ENTITY_ID NVARCHAR(36) NOT NULL,
  SYSTEM_CODE NVARCHAR(128) NOT NULL,
  EXTERNAL_KEY NVARCHAR(512) NOT NULL,
  MATCH_METHOD NVARCHAR(64) NOT NULL,
  MATCH_CONFIDENCE DECIMAL(6,5),
  VERIFIED TINYINT DEFAULT 0 NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UNIQUE(SYSTEM_CODE,EXTERNAL_KEY)
);
CREATE COLUMN TABLE NLP.MDM_ALIAS (
  ALIAS_ID NVARCHAR(36) PRIMARY KEY,
  ENTITY_ID NVARCHAR(36) NOT NULL,
  ALIAS NVARCHAR(512) NOT NULL,
  LANGUAGE_CODE NVARCHAR(32),
  ALIAS_TYPE NVARCHAR(64),
  SOURCE_SYSTEM NVARCHAR(128)
);
CREATE COLUMN TABLE NLP.MDM_PROVENANCE (
  PROVENANCE_ID NVARCHAR(36) PRIMARY KEY,
  ENTITY_ID NVARCHAR(36) NOT NULL,
  SOURCE_URI NCLOB,
  SOURCE_VERSION NVARCHAR(128),
  LICENSE NVARCHAR(512),
  ATTRIBUTION NCLOB,
  RETRIEVED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
