CREATE COLUMN TABLE NLP.DIM_SCRIPT (SCRIPT_KEY BIGINT PRIMARY KEY, CANONICAL_CODE NVARCHAR(64), SCRIPT_NAME NVARCHAR(200), FAMILY_NAME NVARCHAR(200), DECIPHERMENT_STATUS NVARCHAR(32));
CREATE COLUMN TABLE NLP.DIM_MODEL (MODEL_KEY BIGINT PRIMARY KEY, MODEL_NAME NVARCHAR(256), ARCHITECTURE NVARCHAR(128), VERSION NVARCHAR(128), FRAMEWORK NVARCHAR(128));
CREATE COLUMN TABLE NLP.DIM_LANGUAGE (LANGUAGE_KEY BIGINT PRIMARY KEY, LANGUAGE_CODE NVARCHAR(64), LANGUAGE_NAME NVARCHAR(200));
CREATE COLUMN TABLE NLP.DIM_DATE (DATE_KEY INTEGER PRIMARY KEY, CALENDAR_DATE DATE, YEAR_NUMBER INTEGER, QUARTER_NUMBER INTEGER, MONTH_NUMBER INTEGER, DAY_NUMBER INTEGER);
CREATE COLUMN TABLE NLP.FACT_OCR_TRANSLATION (FACT_KEY BIGINT PRIMARY KEY, DATE_KEY INTEGER, SCRIPT_KEY BIGINT, MODEL_KEY BIGINT, SOURCE_LANGUAGE_KEY BIGINT, TARGET_LANGUAGE_KEY BIGINT, GLYPH_COUNT BIGINT, TOKEN_COUNT BIGINT, CONFIDENCE DECIMAL(9,6), LATENCY_MS DECIMAL(20,3), TRANSLATION_COUNT BIGINT, HUMAN_VERIFIED_COUNT BIGINT);
